pipelines:
  file_clickhouse:
    input:
      type: file
    actions:
      - type: set_time
        format: unixtime
        field: ts
    output:
      type: clickhouse
      address: 127.0.0.1:9001
      table: test_table_insert
      db_request_timeout: 1m
      columns:
        - name: c1
          type: String
        - name: c2
          type: Int8
        - name: c3
          type: Int16
        - name: c4
          type: Nullable(Int16)
        - name: c5
          type: Nullable(String)
        - name: level
          type: Enum8('error'=1, 'warn'=2, 'info'=3, 'debug'=4)
        - name: ts
          type: DateTime
